name: Denylist Request
description: Report missing blockable domain(s).
labels: ["deny"]
assignees: 
  - hagezi
body:
  - type: textarea
    id: domains
    attributes:
      label: Which domain(s) should be blocked?
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: Why should these domain(s) be blocked?
      description: |
        If possible, please name the list versions in which the domain(s) should be blocked.
    validations:
      required: true
